///////////////////////////////////////////////////////////
//  FormularzU_ZJ_Uzupe³nijDaneDostawy.cs
//  Implementation of the Class FormularzU_ZJ_Uzupe³nijDaneDostawy
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:54
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik wprowadza lub edytuje dane dostawy dla zamówienia.
	/// </summary>
	public class FormularzU_ZJ_Uzupe³nijDaneDostawy {

		private Dane.Dostawa dostawa;
		private string komunikat;

		public FormularzU_ZJ_Uzupe³nijDaneDostawy(){

		}

		~FormularzU_ZJ_Uzupe³nijDaneDostawy(){

		}

		public Ster_ZJ_Uzupe³nijDaneDostawy Ster_ZJ_Uzupe³nijDaneDostawy{
			get{
				return m_Ster_ZJ_Uzupe³nijDaneDostawy;
			}
			set{
				m_Ster_ZJ_Uzupe³nijDaneDostawy = value;
			}
		}

		public void UzupelnijDaneDostawy(){

		}

		public string WyswietlKomunikat(){

			return "";
		}

	}//end FormularzU_ZJ_Uzupe³nijDaneDostawy

}//end namespace Interfejsy