///////////////////////////////////////////////////////////
//  FormularzA_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT.cs
//  Implementation of the Class FormularzA_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:09
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator uzyskuje dostêp do szczegó³owych danych o zamówieniu sprzêtu IT.
	/// </summary>
	public class FormularzA_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT {

		private Dane.Zamówienie Zamówienie;

		public FormularzA_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT(){

		}

		~FormularzA_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT(){

		}

		public void SprawdŸSzczegó³yZamówieniaSprzêtuIT(){

		}

		public Ster_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT Ster_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT{
			get{
				return m_Ster_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT;
			}
			set{
				m_Ster_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT = value;
			}
		}

		public void WyœwietlSzczegó³yZamówienia(){

		}

	}//end FormularzA_ZS_SprawdŸSzczegó³yZamówieniaSprzêtuIT

}//end namespace Interfejsy