///////////////////////////////////////////////////////////
//  FormularzA_ZR_Przegl¹dajUtworzoneRezerwacje.cs
//  Implementation of the Class FormularzA_ZR_Przegl¹dajUtworzoneRezerwacje
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:30
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator przegl¹da listê rezerwacji u¿ytkowników z mo¿liwoœci¹ filtrowania
	/// wed³ug kryteriów.
	/// </summary>
	public class FormularzA_ZR_Przegl¹dajUtworzoneRezerwacje {

		public FormularzA_ZR_Przegl¹dajUtworzoneRezerwacje(){

		}

		~FormularzA_ZR_Przegl¹dajUtworzoneRezerwacje(){

		}

		public void PrzegladajUtworzoneRezerwacje(){

		}

		public Ster_ZR_Przegl¹dajUtworzoneRezerwacje Ster_ZR_Przegl¹dajUtworzoneRezerwacje{
			get{
				return m_Ster_ZR_Przegl¹dajUtworzoneRezerwacje;
			}
			set{
				m_Ster_ZR_Przegl¹dajUtworzoneRezerwacje = value;
			}
		}

		public Rezerwacje u¿ytkowników WyswietlUtworzoneRezerwacje(){

			return null;
		}

	}//end FormularzA_ZR_Przegl¹dajUtworzoneRezerwacje

}//end namespace Interfejsy