///////////////////////////////////////////////////////////
//  FormularzA_ZS_WyœwietlAnalizeDanychORezerwacjach.cs
//  Implementation of the Class FormularzA_ZS_WyœwietlAnalizeDanychORezerwacjach
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:18
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator ma dostêp do analizy i statystyk dotycz¹cych rezerwacji.
	/// </summary>
	public class FormularzA_ZS_WyœwietlAnalizeDanychORezerwacjach {

		private List(Rezerwacja) Raport;

		public FormularzA_ZS_WyœwietlAnalizeDanychORezerwacjach(){

		}

		~FormularzA_ZS_WyœwietlAnalizeDanychORezerwacjach(){

		}

		public void PobierzAnalizeDanychORezerwacjach(){

		}

		public Ster_ZS_WyœwietlAnalizêDanychORezerwacjach Ster_ZS_WyœwietlAnalizêDanychORezerwacjach{
			get{
				return m_Ster_ZS_WyœwietlAnalizêDanychORezerwacjach;
			}
			set{
				m_Ster_ZS_WyœwietlAnalizêDanychORezerwacjach = value;
			}
		}

	}//end FormularzA_ZS_WyœwietlAnalizeDanychORezerwacjach

}//end namespace Interfejsy