///////////////////////////////////////////////////////////
//  FormularzA_ZIT_UtwórzNoweZamówienieSprzêtuIT.cs
//  Implementation of the Class FormularzA_ZIT_UtwórzNoweZamówienieSprzêtuIT
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:16
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator mo¿e z³o¿yæ nowe zamówienie na sprzêt IT, wybieraj¹c dostawcê i
	/// parametry.
	/// </summary>
	public class FormularzA_ZIT_UtwórzNoweZamówienieSprzêtuIT {

		public FormularzA_ZIT_UtwórzNoweZamówienieSprzêtuIT(){

		}

		~FormularzA_ZIT_UtwórzNoweZamówienieSprzêtuIT(){

		}

		public Ster_ZIT_UtwórzNoweZamówienieSprzêtuIT Ster_ZIT_UtwórzNoweZamówienieSprzêtuIT{
			get{
				return m_Ster_ZIT_UtwórzNoweZamówienieSprzêtuIT;
			}
			set{
				m_Ster_ZIT_UtwórzNoweZamówienieSprzêtuIT = value;
			}
		}

		/// 
		/// <param name="sprzet"></param>
		public void UtworzNoweZamowienieSprzetuIT(Sprzêt IT sprzet){

		}

		public string WyswietlInformacjeOBledzie(){

			return "";
		}

		public Sprzêt IT WyswietlSzczegolyZamowienia(){

			return null;
		}

	}//end FormularzA_ZIT_UtwórzNoweZamówienieSprzêtuIT

}//end namespace Interfejsy