///////////////////////////////////////////////////////////
//  FormularzA_ZS_Zarz¹dzajZasobamiISprzêtemIT.cs
//  Implementation of the Class FormularzA_ZS_Zarz¹dzajZasobamiISprzêtemIT
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:33
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator monitoruje i zarz¹dza dostêpnoœci¹ zasobów oraz sprzêtu IT w
	/// systemie.
	/// </summary>
	public class FormularzA_ZS_Zarz¹dzajZasobamiISprzêtemIT {

		private string czas;
		private string data;
		private string dostêpnoœæ;
		private int SprzêtIT;
		private int Zasób;

		public FormularzA_ZS_Zarz¹dzajZasobamiISprzêtemIT(){

		}

		~FormularzA_ZS_Zarz¹dzajZasobamiISprzêtemIT(){

		}

		public Ster_ZS_Zarz¹dzajZasobamiISprzêtemIT Ster_ZS_Zarz¹dzajZasobamiISprzêtemIT{
			get{
				return m_Ster_ZS_Zarz¹dzajZasobamiISprzêtemIT;
			}
			set{
				m_Ster_ZS_Zarz¹dzajZasobamiISprzêtemIT = value;
			}
		}

		public void WyœwietlKomunikat(){

		}

		public void Zarz¹dzaj(){

		}

	}//end FormularzA_ZS_Zarz¹dzajZasobamiISprzêtemIT

}//end namespace Interfejsy