///////////////////////////////////////////////////////////
//  FormularzA_ZS_EdytujDaneU¿ytkownika.cs
//  Implementation of the Class FormularzA_ZS_EdytujDaneU¿ytkownika
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:50
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator aktualizuje dane u¿ytkownika, np. adres e-mail, rolê czy inne
	/// informacje.
	/// </summary>
	public class FormularzA_ZS_EdytujDaneU¿ytkownika {

		private int tresc;
		private int tytul;
		private Dane.Uzytkownik Uzytkownik;

		public FormularzA_ZS_EdytujDaneU¿ytkownika(){

		}

		~FormularzA_ZS_EdytujDaneU¿ytkownika(){

		}

		public void EdytujDaneUzytkownika(){

		}

		public Ster_ZS_EdytujDaneU¿ytkownika Ster_ZS_EdytujDaneU¿ytkownika{
			get{
				return m_Ster_ZS_EdytujDaneU¿ytkownika;
			}
			set{
				m_Ster_ZS_EdytujDaneU¿ytkownika = value;
			}
		}

		public void WyswietlPowiadomienie(){

		}

	}//end FormularzA_ZS_EdytujDaneU¿ytkownika

}//end namespace Interfejsy