///////////////////////////////////////////////////////////
//  FormularzS_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia.cs
//  Implementation of the Class FormularzS_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:35
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator wysy³a powiadomienie do u¿ytkownika o anulowaniu jego zamówienia
	/// sprzêtu IT.
	/// </summary>
	public class FormularzS_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia {

		private Dane.Administrator odbiorca;
		private string treœæ;
		private string tytu³;
		private Dane.Zamówienie zamowienie;

		public FormularzS_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia(){

		}

		~FormularzS_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia(){

		}

		public Ster_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia Ster_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia{
			get{
				return m_Ster_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia;
			}
			set{
				m_Ster_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia = value;
			}
		}

		public Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji{
			get{
				return m_Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji;
			}
			set{
				m_Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji = value;
			}
		}

		public Ster_ZR_WyœlijPowiadomienieORezerwacji Ster_ZR_WyœlijPowiadomienieORezerwacji{
			get{
				return m_Ster_ZR_WyœlijPowiadomienieORezerwacji;
			}
			set{
				m_Ster_ZR_WyœlijPowiadomienieORezerwacji = value;
			}
		}

		/// 
		/// <param name="zamowienie"></param>
		public void WyslijPowiadomienieOAnulowaniuZamowienia(Zamówienie zamowienie){

		}

	}//end FormularzS_ZIT_WyœlijPowiadomienieOAnulowaniuZamówienia

}//end namespace Interfejsy