///////////////////////////////////////////////////////////
//  FormularzU_ZIT_WeryfikujDostêpnoœæSprzêtuIT.cs
//  Implementation of the Class FormularzU_ZIT_WeryfikujDostêpnoœæSprzêtuIT
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:47
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik mo¿e zweryfikowaæ dostêpnoœæ wybranego sprzêtu przed finalizacj¹
	/// zamówienia.
	/// </summary>
	public class FormularzU_ZIT_WeryfikujDostêpnoœæSprzêtuIT {

		private Sprzêt IT sprzet;

		public FormularzU_ZIT_WeryfikujDostêpnoœæSprzêtuIT(){

		}

		~FormularzU_ZIT_WeryfikujDostêpnoœæSprzêtuIT(){

		}

		public Ster_ZIT_WeryfikujDostêpnoœæSprzêtuIT Ster_ZIT_WeryfikujDostêpnoœæSprzêtuIT{
			get{
				return m_Ster_ZIT_WeryfikujDostêpnoœæSprzêtuIT;
			}
			set{
				m_Ster_ZIT_WeryfikujDostêpnoœæSprzêtuIT = value;
			}
		}

		/// 
		/// <param name="sprzet"></param>
		public void WeryfikujDostepnoscSprzetuIT(Sprzêt IT sprzet){

		}

		public string WyswietlDostepnoscSprzetuIT(){

			return "";
		}

	}//end FormularzU_ZIT_WeryfikujDostêpnoœæSprzêtuIT

}//end namespace Interfejsy