///////////////////////////////////////////////////////////
//  FormularzU_ZR_Zarz퉐zajRezerwacjami.cs
//  Implementation of the Class FormularzU_ZR_Zarz퉐zajRezerwacjami
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:53:21
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U퓓tkownik zarz퉐za swoimi rezerwacjami, np. edytuje, anuluje lub zmienia
	/// szczeg車y.
	/// </summary>
	public class FormularzU_ZR_Zarz퉐zajRezerwacjami {

		public FormularzU_ZR_Zarz퉐zajRezerwacjami(){

		}

		~FormularzU_ZR_Zarz퉐zajRezerwacjami(){

		}

		public Ster_ZR_Zarz퉐zajRezerwacjami Ster_ZR_Zarz퉐zajRezerwacjami{
			get{
				return m_Ster_ZR_Zarz퉐zajRezerwacjami;
			}
			set{
				m_Ster_ZR_Zarz퉐zajRezerwacjami = value;
			}
		}

		public void WyswietlPowiadomienie(){

		}

		/// 
		/// <param name="rezerwacja"></param>
		public void ZmienRezerwacje(Rezerwacja rezerwacja){

		}

	}//end FormularzU_ZR_Zarz퉐zajRezerwacjami

}//end namespace Interfejsy