///////////////////////////////////////////////////////////
//  FormularzA_ZIT_EdytujZamówienie.cs
//  Implementation of the Class FormularzA_ZIT_EdytujZamówienie
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:08
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator ma mo¿liwoœæ edycji zamówienia sprzêtu IT, np. zmiany iloœci lub
	/// terminu dostawy.
	/// </summary>
	public class FormularzA_ZIT_EdytujZamówienie {

		private Dane.Zamówienie zamowienie;

		public FormularzA_ZIT_EdytujZamówienie(){

		}

		~FormularzA_ZIT_EdytujZamówienie(){

		}

		/// 
		/// <param name="zamowienie"></param>
		public void EdytujZamowienie(Zamówienie zamowienie){

		}

		public Ster_ZIT_EdytujZamówienie Ster_ZIT_EdytujZamówienie{
			get{
				return m_Ster_ZIT_EdytujZamówienie;
			}
			set{
				m_Ster_ZIT_EdytujZamówienie = value;
			}
		}

		public treœæ, temat WyswietlPowiadomienie(){

			return null;
		}

	}//end FormularzA_ZIT_EdytujZamówienie

}//end namespace Interfejsy