///////////////////////////////////////////////////////////
//  FormularzU_ZR_EdytujRezerwacje.cs
//  Implementation of the Class FormularzU_ZR_EdytujRezerwacje
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:53:04
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik edytuje swoj¹ rezerwacjê, np. zmienia termin lub liczbê osób.
	/// </summary>
	public class FormularzU_ZR_EdytujRezerwacje {

		public FormularzU_ZR_EdytujRezerwacje(){

		}

		~FormularzU_ZR_EdytujRezerwacje(){

		}

		/// 
		/// <param name="rezerwacja"></param>
		public void EdytujRezerwacje(Rezerwacja rezerwacja){

		}

		public Ster_ZR_EdytujRezerwacjê Ster_ZR_EdytujRezerwacjê{
			get{
				return m_Ster_ZR_EdytujRezerwacjê;
			}
			set{
				m_Ster_ZR_EdytujRezerwacjê = value;
			}
		}

		public void WyswietlPowiadomienie(){

		}

	}//end FormularzU_ZR_EdytujRezerwacje

}//end namespace Interfejsy