///////////////////////////////////////////////////////////
//  FormularzA_ZIT_Przegl¹dajUtworzoneZamówienia.cs
//  Implementation of the Class FormularzA_ZIT_Przegl¹dajUtworzoneZamówienia
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:13
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator przegl¹da listê zamówieñ sprzêtu IT, filtruj¹c wed³ug statusu i
	/// u¿ytkownika.
	/// </summary>
	public class FormularzA_ZIT_Przegl¹dajUtworzoneZamówienia {

		public FormularzA_ZIT_Przegl¹dajUtworzoneZamówienia(){

		}

		~FormularzA_ZIT_Przegl¹dajUtworzoneZamówienia(){

		}

		public sbyte PrzegladajUtworzoneZamowienia(){

			return 0;
		}

		public Ster_ZIT_Przegl¹dajUtworzoneZamówienia Ster_ZIT_Przegl¹dajUtworzoneZamówienia{
			get{
				return m_Ster_ZIT_Przegl¹dajUtworzoneZamówienia;
			}
			set{
				m_Ster_ZIT_Przegl¹dajUtworzoneZamówienia = value;
			}
		}

		public Historia zamówieñ WyswietlUtworzoneZamowienia(){

			return null;
		}

	}//end FormularzA_ZIT_Przegl¹dajUtworzoneZamówienia

}//end namespace Interfejsy