///////////////////////////////////////////////////////////
//  FormularzA_ZIT_AnulujZamówienie.cs
//  Implementation of the Class FormularzA_ZIT_AnulujZamówienie
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:50:59
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator mo¿e anulowaæ zamówienie sprzêtu IT, informuj¹c u¿ytkownika o
	/// zmianie statusu.
	/// </summary>
	public class FormularzA_ZIT_AnulujZamówienie {

		private sbyte zamówienie;

		public FormularzA_ZIT_AnulujZamówienie(){

		}

		~FormularzA_ZIT_AnulujZamówienie(){

		}

		/// 
		/// <param name="zamowienie"></param>
		public void AnulujZamowienie(Zamówienie zamowienie){

		}

		public Ster_ZIT_AnulujZamówienie Ster_ZIT_AnulujZamówienie{
			get{
				return m_Ster_ZIT_AnulujZamówienie;
			}
			set{
				m_Ster_ZIT_AnulujZamówienie = value;
			}
		}

		public treœæ, tytu³ WyswietlPowiadomienie(){

			return null;
		}

	}//end FormularzA_ZIT_AnulujZamówienie

}//end namespace Interfejsy