///////////////////////////////////////////////////////////
//  FormularzA_ZS_UsuñU¿ytkownika.cs
//  Implementation of the Class FormularzA_ZS_UsuñU¿ytkownika
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:14
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator usuwa konto u¿ytkownika z systemu.
	/// </summary>
	public class FormularzA_ZS_UsuñU¿ytkownika {

		private Dane.Uzytkownik uzytkownik;

		public FormularzA_ZS_UsuñU¿ytkownika(){

		}

		~FormularzA_ZS_UsuñU¿ytkownika(){

		}

		public Ster_ZS_UsuñU¿ytkownika Ster_ZS_UsuñU¿ytkownika{
			get{
				return m_Ster_ZS_UsuñU¿ytkownika;
			}
			set{
				m_Ster_ZS_UsuñU¿ytkownika = value;
			}
		}

		/// 
		/// <param name="uzytkownik_id"></param>
		public void UsunUzytkownika(int uzytkownik_id){

		}

		public string WyswietlPotwierdzenieUsuniecia(){

			return "";
		}

	}//end FormularzA_ZS_UsuñU¿ytkownika

}//end namespace Interfejsy