///////////////////////////////////////////////////////////
//  FormularzU_ZIT_EdytujZamówienie.cs
//  Implementation of the Class FormularzU_ZIT_EdytujZamówienie
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:41
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik edytuje swoje zamówienie, np. zmienia iloœæ lub typ zamówionego
	/// sprzêtu.
	/// </summary>
	public class FormularzU_ZIT_EdytujZamówienie {

		private Dane.Zamówienie zamowienie;

		public FormularzU_ZIT_EdytujZamówienie(){

		}

		~FormularzU_ZIT_EdytujZamówienie(){

		}

		/// 
		/// <param name="zamowienie"></param>
		public void EdytujZamowienie(Zamówienie zamowienie){

		}

		public Ster_ZIT_EdytujZamówienie Ster_ZIT_EdytujZamówienie{
			get{
				return m_Ster_ZIT_EdytujZamówienie;
			}
			set{
				m_Ster_ZIT_EdytujZamówienie = value;
			}
		}

		public treœæ, tytu³ WyswietlPowiadomienie(){

			return null;
		}

	}//end FormularzU_ZIT_EdytujZamówienie

}//end namespace Interfejsy