///////////////////////////////////////////////////////////
//  FormularzA_ZR_WeryfikujDostêpnoœæZasobu.cs
//  Implementation of the Class FormularzA_ZR_WeryfikujDostêpnoœæZasobu
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:38
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator zatwierdza dostêpnoœæ zasobu przed finalizacj¹ rezerwacji,
	/// unikaj¹c konfliktów.
	/// </summary>
	public class FormularzA_ZR_WeryfikujDostêpnoœæZasobu {

		public FormularzA_ZR_WeryfikujDostêpnoœæZasobu(){

		}

		~FormularzA_ZR_WeryfikujDostêpnoœæZasobu(){

		}

		public Ster_ZR_WeryfikujDostêpnoœæZasobu Ster_ZR_WeryfikujDostêpnoœæZasobu{
			get{
				return m_Ster_ZR_WeryfikujDostêpnoœæZasobu;
			}
			set{
				m_Ster_ZR_WeryfikujDostêpnoœæZasobu = value;
			}
		}

		/// 
		/// <param name="rezerwacja"></param>
		public sbyte WeryfikujDostepnoscZasobu(Rezerwacja rezerwacja){

			return 0;
		}

		public Dostêpnoœæ zasobu WyswietlDostepnoscRezerwacji(){

			return null;
		}

	}//end FormularzA_ZR_WeryfikujDostêpnoœæZasobu

}//end namespace Interfejsy