///////////////////////////////////////////////////////////
//  FormularzA_ZS_Zarz¹dzajSystemem.cs
//  Implementation of the Class FormularzA_ZS_Zarz¹dzajSystemem
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:30
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator zarz¹dza g³ównymi ustawieniami systemu, takimi jak konfiguracja
	/// dostêpu i uprawnieñ.
	/// </summary>
	public class FormularzA_ZS_Zarz¹dzajSystemem {

		private Enum Opcja;

		public FormularzA_ZS_Zarz¹dzajSystemem(){

		}

		~FormularzA_ZS_Zarz¹dzajSystemem(){

		}

		public Baza sprzêtu IT Baza sprzêtu IT{
			get{
				return m_Baza sprzêtu IT;
			}
			set{
				m_Baza sprzêtu IT = value;
			}
		}

		public Dostêpnoœæ zasobu Dostêpnoœæ zasobu{
			get{
				return m_Dostêpnoœæ zasobu;
			}
			set{
				m_Dostêpnoœæ zasobu = value;
			}
		}

		public Lista u¿ytkowników Lista u¿ytkowników{
			get{
				return m_Lista u¿ytkowników;
			}
			set{
				m_Lista u¿ytkowników = value;
			}
		}

		public Powiadomienie Powiadomienie{
			get{
				return m_Powiadomienie;
			}
			set{
				m_Powiadomienie = value;
			}
		}

		public Ster_ZS_EdytujRezerwacjeU¿ytkownika Ster_ZS_EdytujRezerwacjeU¿ytkownika{
			get{
				return m_Ster_ZS_EdytujRezerwacjeU¿ytkownika;
			}
			set{
				m_Ster_ZS_EdytujRezerwacjeU¿ytkownika = value;
			}
		}

		public Ster_ZS_Zarz¹dzajSystemem Ster_ZS_Zarz¹dzajSystemem{
			get{
				return m_Ster_ZS_Zarz¹dzajSystemem;
			}
			set{
				m_Ster_ZS_Zarz¹dzajSystemem = value;
			}
		}

		public void Zarz¹dzajSystemem(){

		}

		public Zasob Zasob{
			get{
				return m_Zasob;
			}
			set{
				m_Zasob = value;
			}
		}

	}//end FormularzA_ZS_Zarz¹dzajSystemem

}//end namespace Interfejsy