///////////////////////////////////////////////////////////
//  FormularzA_ZS_UsuñZamówienieU¿ytkownika.cs
//  Implementation of the Class FormularzA_ZS_UsuñZamówienieU¿ytkownika
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:16
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator usuwa konkretne zamówienie u¿ytkownika.
	/// </summary>
	public class FormularzA_ZS_UsuñZamówienieU¿ytkownika {

		private string komunikat;
		private string treœæ;
		private Dane.Zamówienie Zamówienie;

		public FormularzA_ZS_UsuñZamówienieU¿ytkownika(){

		}

		~FormularzA_ZS_UsuñZamówienieU¿ytkownika(){

		}

		public Ster_ZS_UsuñZamówienieU¿ytkownika Ster_ZS_UsuñZamówienieU¿ytkownika{
			get{
				return m_Ster_ZS_UsuñZamówienieU¿ytkownika;
			}
			set{
				m_Ster_ZS_UsuñZamówienieU¿ytkownika = value;
			}
		}

		public void UsuñZamówienieU¿ytkownika(){

		}

		public void WyœwietlKomunikat(){

		}

	}//end FormularzA_ZS_UsuñZamówienieU¿ytkownika

}//end namespace Interfejsy