///////////////////////////////////////////////////////////
//  FormularzU_ZR_UtwórzNow¹Rezerwacje.cs
//  Implementation of the Class FormularzU_ZR_UtwórzNow¹Rezerwacje
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:53:11
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik dokonuje nowej rezerwacji, wybieraj¹c dostêpne terminy i opcje.
	/// </summary>
	public class FormularzU_ZR_UtwórzNow¹Rezerwacje {

		public FormularzU_ZR_UtwórzNow¹Rezerwacje(){

		}

		~FormularzU_ZR_UtwórzNow¹Rezerwacje(){

		}

		public Ster_ZR_UtwórzNow¹Rezerwacjê Ster_ZR_UtwórzNow¹Rezerwacjê{
			get{
				return m_Ster_ZR_UtwórzNow¹Rezerwacjê;
			}
			set{
				m_Ster_ZR_UtwórzNow¹Rezerwacjê = value;
			}
		}

		/// 
		/// <param name="rezerwacja"></param>
		public void UtworzNowaRezerwacje(Rezerwacja rezerwacja){

		}

		public void WyswietlInformacjeOBledzie(){

		}

		public Dane.Rezerwacja WyswietlSzczegolyRezerwacji(){

			return null;
		}

	}//end FormularzU_ZR_UtwórzNow¹Rezerwacje

}//end namespace Interfejsy