///////////////////////////////////////////////////////////
//  FormularzU_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji.cs
//  Implementation of the Class FormularzU_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:53:15
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik wysy³a powiadomienie o anulowanej rezerwacji.
	/// </summary>
	public class FormularzU_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji {

		public FormularzU_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji(){

		}

		~FormularzU_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji(){

		}

		public Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji{
			get{
				return m_Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji;
			}
			set{
				m_Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji = value;
			}
		}

	}//end FormularzU_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji

}//end namespace Interfejsy