///////////////////////////////////////////////////////////
//  FormularzA_ZIT_WyœlijPowiadomienieOZamówieniu.cs
//  Implementation of the Class FormularzA_ZIT_WyœlijPowiadomienieOZamówieniu
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:22
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator informuje u¿ytkownika o statusie jego zamówienia sprzêtu IT.
	/// </summary>
	public class FormularzA_ZIT_WyœlijPowiadomienieOZamówieniu {

		private Dane.Administrator odbiorca;
		private string treœæ;
		private string tytu³;
		private Dane.Zamówienie zamowienie;

		public FormularzA_ZIT_WyœlijPowiadomienieOZamówieniu(){

		}

		~FormularzA_ZIT_WyœlijPowiadomienieOZamówieniu(){

		}

		public Ster_ZIT_WyœlijPowiadomienieOZamówieniu Ster_ZIT_WyœlijPowiadomienieOZamówieniu{
			get{
				return m_Ster_ZIT_WyœlijPowiadomienieOZamówieniu;
			}
			set{
				m_Ster_ZIT_WyœlijPowiadomienieOZamówieniu = value;
			}
		}

		/// 
		/// <param name="zamowienie"></param>
		public void WyslijPowiadomienieOZamowieniu(Zamówienie zamowienie){

		}

	}//end FormularzA_ZIT_WyœlijPowiadomienieOZamówieniu

}//end namespace Interfejsy