///////////////////////////////////////////////////////////
//  FormularzU_ZIT_UtwórzNoweZamówienieSprzêtuIT.cs
//  Implementation of the Class FormularzU_ZIT_UtwórzNoweZamówienieSprzêtuIT
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:45
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik sk³ada nowe zamówienie na sprzêt IT, wybieraj¹c dostêpne opcje.
	/// </summary>
	public class FormularzU_ZIT_UtwórzNoweZamówienieSprzêtuIT {

		public FormularzU_ZIT_UtwórzNoweZamówienieSprzêtuIT(){

		}

		~FormularzU_ZIT_UtwórzNoweZamówienieSprzêtuIT(){

		}

		public Ster_ZIT_UtwórzNoweZamówienieSprzêtuIT Ster_ZIT_UtwórzNoweZamówienieSprzêtuIT{
			get{
				return m_Ster_ZIT_UtwórzNoweZamówienieSprzêtuIT;
			}
			set{
				m_Ster_ZIT_UtwórzNoweZamówienieSprzêtuIT = value;
			}
		}

		/// 
		/// <param name="sprzet"></param>
		public void UtworzNoweZamowienieSprzetuIT(Sprzêt IT sprzet){

		}

		public string WyswietlInformacjeOBledzie(){

			return "";
		}

		public Dane.Zamówienie WyswietlSzczegolyZamowienia(){

			return null;
		}

	}//end FormularzU_ZIT_UtwórzNoweZamówienieSprzêtuIT

}//end namespace Interfejsy