///////////////////////////////////////////////////////////
//  FormularzU_ZR_WyœlijPowiadomienieORezerwacji.cs
//  Implementation of the Class FormularzU_ZR_WyœlijPowiadomienieORezerwacji
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:53:19
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik wysy³a powiadomienie o nowej rezerwacji.
	/// </summary>
	public class FormularzU_ZR_WyœlijPowiadomienieORezerwacji {

		public FormularzU_ZR_WyœlijPowiadomienieORezerwacji(){

		}

		~FormularzU_ZR_WyœlijPowiadomienieORezerwacji(){

		}

		public Ster_ZR_WyœlijPowiadomienieORezerwacji Ster_ZR_WyœlijPowiadomienieORezerwacji{
			get{
				return m_Ster_ZR_WyœlijPowiadomienieORezerwacji;
			}
			set{
				m_Ster_ZR_WyœlijPowiadomienieORezerwacji = value;
			}
		}

	}//end FormularzU_ZR_WyœlijPowiadomienieORezerwacji

}//end namespace Interfejsy