///////////////////////////////////////////////////////////
//  FormularzA_ZS_Zarz¹dzajPowiadomieniami.cs
//  Implementation of the Class FormularzA_ZS_Zarz¹dzajPowiadomieniami
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:28
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator konfiguruje i wysy³a powiadomienia systemowe do u¿ytkowników.
	/// </summary>
	public class FormularzA_ZS_Zarz¹dzajPowiadomieniami {

		public FormularzA_ZS_Zarz¹dzajPowiadomieniami(){

		}

		~FormularzA_ZS_Zarz¹dzajPowiadomieniami(){

		}

		public Ster_ZS_Zarz¹dzajPowiadomieniami Ster_ZS_Zarz¹dzajPowiadomieniami{
			get{
				return m_Ster_ZS_Zarz¹dzajPowiadomieniami;
			}
			set{
				m_Ster_ZS_Zarz¹dzajPowiadomieniami = value;
			}
		}

		public void Zarz¹dzajPowiadomieniami(){

		}

	}//end FormularzA_ZS_Zarz¹dzajPowiadomieniami

}//end namespace Interfejsy