///////////////////////////////////////////////////////////
//  FormularzU_ZJ_Przegl¹dajMenu.cs
//  Implementation of the Class FormularzU_ZJ_Przegl¹dajMenu
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:52
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik przegl¹da dostêpne jedzenia do zamówienia.
	/// </summary>
	public class FormularzU_ZJ_Przegl¹dajMenu {

		public FormularzU_ZJ_Przegl¹dajMenu(){

		}

		~FormularzU_ZJ_Przegl¹dajMenu(){

		}

		public void PrzegladajMenu(){

		}

		public Ster_ZJ_Przegl¹dajMenu Ster_ZJ_Przegl¹dajMenu{
			get{
				return m_Ster_ZJ_Przegl¹dajMenu;
			}
			set{
				m_Ster_ZJ_Przegl¹dajMenu = value;
			}
		}

		public identyfikator, nazwa posilku, opis posilku WyswietlMenu(){

			return null;
		}

	}//end FormularzU_ZJ_Przegl¹dajMenu

}//end namespace Interfejsy