///////////////////////////////////////////////////////////
//  FormularzA_ZS_GenerujRaportORezerwacjach.cs
//  Implementation of the Class FormularzA_ZS_GenerujRaportORezerwacjach
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:57
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator generuje raport podsumowuj¹cy wszystkie rezerwacje w systemie.
	/// </summary>
	public class FormularzA_ZS_GenerujRaportORezerwacjach {

		private Raport Rezerwacji Raport Rezerwacji;

		public FormularzA_ZS_GenerujRaportORezerwacjach(){

		}

		~FormularzA_ZS_GenerujRaportORezerwacjach(){

		}

		public void GenerujRaportORezerwacjach(){

		}

		public Ster_ZS_GenerujRaportORezerwacjach Ster_ZS_GenerujRaportORezerwacjach{
			get{
				return m_Ster_ZS_GenerujRaportORezerwacjach;
			}
			set{
				m_Ster_ZS_GenerujRaportORezerwacjach = value;
			}
		}

		public void Wyœwietl Raport(){

		}

	}//end FormularzA_ZS_GenerujRaportORezerwacjach

}//end namespace Interfejsy