///////////////////////////////////////////////////////////
//  FormularzA_ZS_Zarz¹dzajList¹U¿ytkowników.cs
//  Implementation of the Class FormularzA_ZS_Zarz¹dzajList¹U¿ytkowników
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:26
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator ma dostêp do listy u¿ytkowników i mo¿e ni¹ zarz¹dzaæ.
	/// </summary>
	public class FormularzA_ZS_Zarz¹dzajList¹U¿ytkowników {

		public FormularzA_ZS_Zarz¹dzajList¹U¿ytkowników(){

		}

		~FormularzA_ZS_Zarz¹dzajList¹U¿ytkowników(){

		}

		public Ster_ZS_Zarz¹dzajList¹U¿ytkowników Ster_ZS_Zarz¹dzajList¹U¿ytkowników{
			get{
				return m_Ster_ZS_Zarz¹dzajList¹U¿ytkowników;
			}
			set{
				m_Ster_ZS_Zarz¹dzajList¹U¿ytkowników = value;
			}
		}

		public void WyœwietlPowiadomienie(){

		}

		public void ZmieñListeU¿ytkowników(){

		}

	}//end FormularzA_ZS_Zarz¹dzajList¹U¿ytkowników

}//end namespace Interfejsy