///////////////////////////////////////////////////////////
//  FormularzA_ZS_EdytujZamówienieU¿ytkownika.cs
//  Implementation of the Class FormularzA_ZS_EdytujZamówienieU¿ytkownika
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:55
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator edytuje zamówienie u¿ytkownika, np. zmienia jego status lub
	/// zawartoœæ.
	/// </summary>
	public class FormularzA_ZS_EdytujZamówienieU¿ytkownika {

		private string treœæ;
		private string tytu³;
		private Zamowienie zamowienie;

		public FormularzA_ZS_EdytujZamówienieU¿ytkownika(){

		}

		~FormularzA_ZS_EdytujZamówienieU¿ytkownika(){

		}

		public void EdytujZamowienieUzytkownika(){

		}

		public Ster_ZS_EdytujZamówienieU¿ytkownika Ster_ZS_EdytujZamówienieU¿ytkownika{
			get{
				return m_Ster_ZS_EdytujZamówienieU¿ytkownika;
			}
			set{
				m_Ster_ZS_EdytujZamówienieU¿ytkownika = value;
			}
		}

		public void WyswietlKomunikat(){

		}

	}//end FormularzA_ZS_EdytujZamówienieU¿ytkownika

}//end namespace Interfejsy