///////////////////////////////////////////////////////////
//  FormularzA_ZS_WyœwietlAnalizeDanychOZamówieniach.cs
//  Implementation of the Class FormularzA_ZS_WyœwietlAnalizeDanychOZamówieniach
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:21
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DBTableMate.Tables;
namespace Interfejsy {
	/// <summary>
	/// Administrator analizuje dane dotycz¹ce zamówieñ sprzêtu IT.
	/// </summary>
	public class FormularzA_ZS_WyœwietlAnalizeDanychOZamówieniach {

		private DBTableMate.Tables.RaportZamówieñ RaportZamówieñ;

		public FormularzA_ZS_WyœwietlAnalizeDanychOZamówieniach(){

		}

		~FormularzA_ZS_WyœwietlAnalizeDanychOZamówieniach(){

		}

		public void PobierzAnalizeDanychOZamówieniach(){

		}

		public Ster_ZS_WyœwietlAnalizêDanychOZamówieniach Ster_ZS_WyœwietlAnalizêDanychOZamówieniach{
			get{
				return m_Ster_ZS_WyœwietlAnalizêDanychOZamówieniach;
			}
			set{
				m_Ster_ZS_WyœwietlAnalizêDanychOZamówieniach = value;
			}
		}

		public void WyœwietlAnalizeDanychOZamówieniach(){

		}

	}//end FormularzA_ZS_WyœwietlAnalizeDanychOZamówieniach

}//end namespace Interfejsy