///////////////////////////////////////////////////////////
//  FormularzU_ZIT_Przegl¹dajUtworzoneZamówienia.cs
//  Implementation of the Class FormularzU_ZIT_Przegl¹dajUtworzoneZamówienia
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:43
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik przegl¹da listê swoich dotychczasowych zamówieñ na sprzêt IT.
	/// </summary>
	public class FormularzU_ZIT_Przegl¹dajUtworzoneZamówienia {

		public FormularzU_ZIT_Przegl¹dajUtworzoneZamówienia(){

		}

		~FormularzU_ZIT_Przegl¹dajUtworzoneZamówienia(){

		}

		public sbyte PrzegladajUtworzoneZamowienia(){

			return 0;
		}

		public Ster_ZIT_Przegl¹dajUtworzoneZamówienia Ster_ZIT_Przegl¹dajUtworzoneZamówienia{
			get{
				return m_Ster_ZIT_Przegl¹dajUtworzoneZamówienia;
			}
			set{
				m_Ster_ZIT_Przegl¹dajUtworzoneZamówienia = value;
			}
		}

		public Historia zamówieñ WyswietlUtworzoneZamowienia(){

			return null;
		}

	}//end FormularzU_ZIT_Przegl¹dajUtworzoneZamówienia

}//end namespace Interfejsy