///////////////////////////////////////////////////////////
//  FormularzU_ZIT_AnulujZamówienie.cs
//  Implementation of the Class FormularzU_ZIT_AnulujZamówienie
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:37
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik mo¿e anulowaæ swoje zamówienie na sprzêt IT, jeœli nie zosta³o
	/// jeszcze zrealizowane.
	/// </summary>
	public class FormularzU_ZIT_AnulujZamówienie {

		private Dane.Zamówienie zamowienie;

		public FormularzU_ZIT_AnulujZamówienie(){

		}

		~FormularzU_ZIT_AnulujZamówienie(){

		}

		/// 
		/// <param name="zamowienie"></param>
		public void AnulujZamowienie(Zamówienie zamowienie){

		}

		public Ster_ZIT_AnulujZamówienie Ster_ZIT_AnulujZamówienie{
			get{
				return m_Ster_ZIT_AnulujZamówienie;
			}
			set{
				m_Ster_ZIT_AnulujZamówienie = value;
			}
		}

		public treœæ, tytu³ WyswietlPowiadomienie(){

			return null;
		}

	}//end FormularzU_ZIT_AnulujZamówienie

}//end namespace Interfejsy