///////////////////////////////////////////////////////////
//  FormularzA_ZS_DodajU퓓tkownika.cs
//  Implementation of the Class FormularzA_ZS_DodajU퓓tkownika
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:48
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator dodaje nowego u퓓tkownika do systemu, okre쐋aj퉏 jego dane i
	/// uprawnienia.
	/// </summary>
	public class FormularzA_ZS_DodajU퓓tkownika {

		private string Imie;
		private string Nazwisko;
		private int tresc;
		private int tytul;

		public FormularzA_ZS_DodajU퓓tkownika(){

		}

		~FormularzA_ZS_DodajU퓓tkownika(){

		}

		public void DodajUzytkownika(){

		}

		public Ster_ZS_DodajU퓓tkownika Ster_ZS_DodajU퓓tkownika{
			get{
				return m_Ster_ZS_DodajU퓓tkownika;
			}
			set{
				m_Ster_ZS_DodajU퓓tkownika = value;
			}
		}

		public void WyswietlPowiadomienie(){

		}

	}//end FormularzA_ZS_DodajU퓓tkownika

}//end namespace Interfejsy