///////////////////////////////////////////////////////////
//  FormularzU_ZR_WeryfikujDostêpnoœæZasobu.cs
//  Implementation of the Class FormularzU_ZR_WeryfikujDostêpnoœæZasobu
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:53:13
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik weryfikuje dostêpnoœæ konkretnego zasobu przed finalizacj¹
	/// rezerwacji.
	/// </summary>
	public class FormularzU_ZR_WeryfikujDostêpnoœæZasobu {

		private Sprzêt IT sprzet;

		public FormularzU_ZR_WeryfikujDostêpnoœæZasobu(){

		}

		~FormularzU_ZR_WeryfikujDostêpnoœæZasobu(){

		}

		public void operation1(){

		}

		public Ster_ZR_WeryfikujDostêpnoœæZasobu Ster_ZR_WeryfikujDostêpnoœæZasobu{
			get{
				return m_Ster_ZR_WeryfikujDostêpnoœæZasobu;
			}
			set{
				m_Ster_ZR_WeryfikujDostêpnoœæZasobu = value;
			}
		}

		/// 
		/// <param name="sprzet"></param>
		public sbyte WeryfikujDostepnoscZasobu(Sprzêt IT sprzet){

			return 0;
		}

		/// 
		/// <param name="rezerwacja"></param>
		public sbyte WeryfikujDostepnoscZasobu(Rezerwacja rezerwacja){

			return 0;
		}

		public Dostêpnoœæ zasobu WyswietlDostepnoscRezerwacji(){

			return null;
		}

		public Dostêpnoœæ zasobu WyswietlDostepnoscSprzetuIT(){

			return null;
		}

	}//end FormularzU_ZR_WeryfikujDostêpnoœæZasobu

}//end namespace Interfejsy