///////////////////////////////////////////////////////////
//  FormularzU_ZR_SprzawdŸDostêpnoœæZasobów.cs
//  Implementation of the Class FormularzU_ZR_SprzawdŸDostêpnoœæZasobów
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:53:09
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik sprawdza dostêpnoœæ zasobów przed dokonaniem rezerwacji.
	/// </summary>
	public class FormularzU_ZR_SprzawdŸDostêpnoœæZasobów {

		public FormularzU_ZR_SprzawdŸDostêpnoœæZasobów(){

		}

		~FormularzU_ZR_SprzawdŸDostêpnoœæZasobów(){

		}

		/// 
		/// <param name="rezerwacja"></param>
		public void SprawdzDostepnoscZasobu(Rezerwacja rezerwacja){

		}

		public Ster_ZR_SprawdŸDostêpnoœæZasobów Ster_ZR_SprawdŸDostêpnoœæZasobów{
			get{
				return m_Ster_ZR_SprawdŸDostêpnoœæZasobów;
			}
			set{
				m_Ster_ZR_SprawdŸDostêpnoœæZasobów = value;
			}
		}

		public void WyswietlDostepnoscZasobu(){

		}

	}//end FormularzU_ZR_SprzawdŸDostêpnoœæZasobów

}//end namespace Interfejsy