///////////////////////////////////////////////////////////
//  FormularzU_ZJ_Z³ó¿Zamówienie.cs
//  Implementation of the Class FormularzU_ZJ_Z³ó¿Zamówienie
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:59
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik sk³ada nowe zamówienie na wybrane produkty lub us³ugi.
	/// </summary>
	public class FormularzU_ZJ_Z³ó¿Zamówienie {

		private string data;
		private Dane.Dostawa dostawa;
		private string Imie;
		private string Nazwisko;
		private Posilek posilek;

		public FormularzU_ZJ_Z³ó¿Zamówienie(){

		}

		~FormularzU_ZJ_Z³ó¿Zamówienie(){

		}

		public string PokazPowiadomienie(){

			return "";
		}

		public Ster_ZJ_Z³ó¿Zamówienie Ster_ZJ_Z³ó¿Zamówienie{
			get{
				return m_Ster_ZJ_Z³ó¿Zamówienie;
			}
			set{
				m_Ster_ZJ_Z³ó¿Zamówienie = value;
			}
		}

		public void ZlozZamowienie(){

		}

	}//end FormularzU_ZJ_Z³ó¿Zamówienie

}//end namespace Interfejsy