///////////////////////////////////////////////////////////
//  FormularzA_ZR_UtwórzNow¹Rezerwacje.cs
//  Implementation of the Class FormularzA_ZR_UtwórzNow¹Rezerwacje
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:35
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator mo¿e rêcznie utworzyæ now¹ rezerwacjê w imieniu u¿ytkownika lub
	/// na potrzeby systemowe.
	/// </summary>
	public class FormularzA_ZR_UtwórzNow¹Rezerwacje {

		public FormularzA_ZR_UtwórzNow¹Rezerwacje(){

		}

		~FormularzA_ZR_UtwórzNow¹Rezerwacje(){

		}

		public Ster_ZR_UtwórzNow¹Rezerwacjê Ster_ZR_UtwórzNow¹Rezerwacjê{
			get{
				return m_Ster_ZR_UtwórzNow¹Rezerwacjê;
			}
			set{
				m_Ster_ZR_UtwórzNow¹Rezerwacjê = value;
			}
		}

		/// 
		/// <param name="rezerwacja"></param>
		public void UtworzNowaRezerwacje(Rezerwacja rezerwacja){

		}

		public Dane.Rezerwacja WyswietlSzczegolyRezerwacji(){

			return null;
		}

	}//end FormularzA_ZR_UtwórzNow¹Rezerwacje

}//end namespace Interfejsy