///////////////////////////////////////////////////////////
//  FormularzU_ZJ_Przegl¹dajHistorieZamówieñ.cs
//  Implementation of the Class FormularzU_ZJ_Przegl¹dajHistorieZamówieñ
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:50
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik przegl¹da historiê swoich zamówieñ.
	/// </summary>
	public class FormularzU_ZJ_Przegl¹dajHistorieZamówieñ {

		private string data;

		public FormularzU_ZJ_Przegl¹dajHistorieZamówieñ(){

		}

		~FormularzU_ZJ_Przegl¹dajHistorieZamówieñ(){

		}

		public void PrzegladajZamowienia(){

		}

		public Ster_ZJ_Przegl¹dajHistoriêZamówieñ Ster_ZJ_Przegl¹dajHistoriêZamówieñ{
			get{
				return m_Ster_ZJ_Przegl¹dajHistoriêZamówieñ;
			}
			set{
				m_Ster_ZJ_Przegl¹dajHistoriêZamówieñ = value;
			}
		}

		public List(Zamowienie) WyswietlZamowienia(){

			return null;
		}

		public identyfikator zamowienia, data, dostawa, posilek, nazwa, opis WyswietlZamowienia(){

			return null;
		}

	}//end FormularzU_ZJ_Przegl¹dajHistorieZamówieñ

}//end namespace Interfejsy