///////////////////////////////////////////////////////////
//  FormularzA_ZS_EdytujRezerwacjeU퓓tkownika.cs
//  Implementation of the Class FormularzA_ZS_EdytujRezerwacjeU퓓tkownika
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:52
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator modyfikuje rezerwacje przypisane do konkretnego u퓓tkownika.
	/// </summary>
	public class FormularzA_ZS_EdytujRezerwacjeU퓓tkownika {

		private Dane.Rezerwacja rezerwacja;
		private string tresc;
		private string tytu�;

		public FormularzA_ZS_EdytujRezerwacjeU퓓tkownika(){

		}

		~FormularzA_ZS_EdytujRezerwacjeU퓓tkownika(){

		}

		public void EdytujRezerwacje(){

		}

		public Ster_ZS_EdytujRezerwacjeU퓓tkownika Ster_ZS_EdytujRezerwacjeU퓓tkownika{
			get{
				return m_Ster_ZS_EdytujRezerwacjeU퓓tkownika;
			}
			set{
				m_Ster_ZS_EdytujRezerwacjeU퓓tkownika = value;
			}
		}

		public void Wy쐗ietlKomunikat(){

		}

	}//end FormularzA_ZS_EdytujRezerwacjeU퓓tkownika

}//end namespace Interfejsy