///////////////////////////////////////////////////////////
//  FormularzA_ZS_UsuñRezerwacjeU¿ytkownika.cs
//  Implementation of the Class FormularzA_ZS_UsuñRezerwacjeU¿ytkownika
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:12
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator usuwa rezerwacjê przypisan¹ do u¿ytkownika.
	/// </summary>
	public class FormularzA_ZS_UsuñRezerwacjeU¿ytkownika {

		private Dane.Rezerwacja Rezerwacja;
		private string treœæ;
		private string tytu³;

		public FormularzA_ZS_UsuñRezerwacjeU¿ytkownika(){

		}

		~FormularzA_ZS_UsuñRezerwacjeU¿ytkownika(){

		}

		public Ster_ZS_UsuñRezerwacjeU¿ytkownika Ster_ZS_UsuñRezerwacjeU¿ytkownika{
			get{
				return m_Ster_ZS_UsuñRezerwacjeU¿ytkownika;
			}
			set{
				m_Ster_ZS_UsuñRezerwacjeU¿ytkownika = value;
			}
		}

		public void UsuñRezerwacjeU¿ytkownika(){

		}

		public void WyœwietlKomunikat(){

		}

	}//end FormularzA_ZS_UsuñRezerwacjeU¿ytkownika

}//end namespace Interfejsy