///////////////////////////////////////////////////////////
//  FormularzU_ZR_Przegl¹dajUtworzoneRezerwacje.cs
//  Implementation of the Class FormularzU_ZR_Przegl¹dajUtworzoneRezerwacje
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:53:06
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik przegl¹da swoje aktywne i zakoñczone rezerwacje.
	/// </summary>
	public class FormularzU_ZR_Przegl¹dajUtworzoneRezerwacje {

		public FormularzU_ZR_Przegl¹dajUtworzoneRezerwacje(){

		}

		~FormularzU_ZR_Przegl¹dajUtworzoneRezerwacje(){

		}

		public void PrzegladajUtworzoneRezerwacje(){

		}

		public Ster_ZR_Przegl¹dajUtworzoneRezerwacje Ster_ZR_Przegl¹dajUtworzoneRezerwacje{
			get{
				return m_Ster_ZR_Przegl¹dajUtworzoneRezerwacje;
			}
			set{
				m_Ster_ZR_Przegl¹dajUtworzoneRezerwacje = value;
			}
		}

		public Rezerwacje u¿ytkowników WyswietlUtworzoneRezerwacje(){

			return null;
		}

	}//end FormularzU_ZR_Przegl¹dajUtworzoneRezerwacje

}//end namespace Interfejsy