///////////////////////////////////////////////////////////
//  FormularzU_ZJ_Zarz¹dzajZamówieniami.cs
//  Implementation of the Class FormularzU_ZJ_Zarz¹dzajZamówieniami
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:57
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// U¿ytkownik zarz¹dza swoimi zamówieniami (edycja, anulowanie, podgl¹d statusu).
	/// </summary>
	public class FormularzU_ZJ_Zarz¹dzajZamówieniami {

		private string data;
		private Dane.Dostawa dostawa;
		private Posilek posilek;
		private string powiadomienie;

		public FormularzU_ZJ_Zarz¹dzajZamówieniami(){

		}

		~FormularzU_ZJ_Zarz¹dzajZamówieniami(){

		}

		public Ster_ZJ_Zarz¹dzajZamówieniami Ster_ZJ_Zarz¹dzajZamówieniami{
			get{
				return m_Ster_ZJ_Zarz¹dzajZamówieniami;
			}
			set{
				m_Ster_ZJ_Zarz¹dzajZamówieniami = value;
			}
		}

		public void WyswietlPowiadomienie(){

		}

		public void ZmienZamowienie(){

		}

	}//end FormularzU_ZJ_Zarz¹dzajZamówieniami

}//end namespace Interfejsy