///////////////////////////////////////////////////////////
//  FormularzA_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji.cs
//  Implementation of the Class FormularzA_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:40
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator wysy³a u¿ytkownikowi powiadomienie o anulowaniu jego rezerwacji.
	/// </summary>
	public class FormularzA_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji {

		public FormularzA_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji(){

		}

		~FormularzA_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji(){

		}

		public Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji{
			get{
				return m_Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji;
			}
			set{
				m_Ster_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji = value;
			}
		}

		/// 
		/// <param name="rezerwacja"></param>
		public void WyslijPowiadomienieOAnulowaniuRezerwacji(Rezerwacja rezerwacja){

		}

	}//end FormularzA_ZR_WyœlijPowiadomienieOAnulowaniuRezerwacji

}//end namespace Interfejsy