///////////////////////////////////////////////////////////
//  FormularzA_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników.cs
//  Implementation of the Class FormularzA_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:03
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator ma dostêp do wszystkich rezerwacji u¿ytkowników i mo¿e je
	/// przegl¹daæ.
	/// </summary>
	public class FormularzA_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników {

		private Rezerwacje U¿ytkowników RezerwacjeU¿ytkowników;

		public FormularzA_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników(){

		}

		~FormularzA_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników(){

		}

		public void Przegl¹dajWszystkieRezerwacje(){

		}

		public Ster_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników Ster_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników{
			get{
				return m_Ster_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników;
			}
			set{
				m_Ster_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników = value;
			}
		}

		public void WyœwietlRezerwacje(){

		}

	}//end FormularzA_ZS_Przegl¹dajWszystkieRezerwacjeU¿ytkowników

}//end namespace Interfejsy