///////////////////////////////////////////////////////////
//  FormularzA_ZS_Wy쐗ietlDaneU퓓tkownika.cs
//  Implementation of the Class FormularzA_ZS_Wy쐗ietlDaneU퓓tkownika
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:23
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator przegl퉐a szczeg車owe informacje o u퓓tkowniku.
	/// </summary>
	public class FormularzA_ZS_Wy쐗ietlDaneU퓓tkownika {

		private U퓓tkownik U퓓tkownik;

		public FormularzA_ZS_Wy쐗ietlDaneU퓓tkownika(){

		}

		~FormularzA_ZS_Wy쐗ietlDaneU퓓tkownika(){

		}

		public void PobierzDaneU퓓tkownika(){

		}

		public Ster_ZS_Wy쐗ietlDaneU퓓tkownika Ster_ZS_Wy쐗ietlDaneU퓓tkownika{
			get{
				return m_Ster_ZS_Wy쐗ietlDaneU퓓tkownika;
			}
			set{
				m_Ster_ZS_Wy쐗ietlDaneU퓓tkownika = value;
			}
		}

		public void Wy쐗ietlDaneU퓓tkownika(){

		}

	}//end FormularzA_ZS_Wy쐗ietlDaneU퓓tkownika

}//end namespace Interfejsy