///////////////////////////////////////////////////////////
//  FormularzA_ZS_GenerujRaportOZamówieniach.cs
//  Implementation of the Class FormularzA_ZS_GenerujRaportOZamówieniach
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:00
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DBTableMate.Tables;
namespace Interfejsy {
	/// <summary>
	/// Administrator tworzy raport dotycz¹cy zamówieñ sprzêtu IT z³o¿onych przez
	/// u¿ytkowników.
	/// </summary>
	public class FormularzA_ZS_GenerujRaportOZamówieniach {

		private DBTableMate.Tables.RaportZamówieñ RaportZamówieñ;

		public FormularzA_ZS_GenerujRaportOZamówieniach(){

		}

		~FormularzA_ZS_GenerujRaportOZamówieniach(){

		}

		public void GenerujRaportOZamówieniach(){

		}

		public Ster_ZS_GenerujRaportOZamówieniach Ster_ZS_GenerujRaportOZamówieniach{
			get{
				return m_Ster_ZS_GenerujRaportOZamówieniach;
			}
			set{
				m_Ster_ZS_GenerujRaportOZamówieniach = value;
			}
		}

		public void WyœwietlRaportZamówieñ(){

		}

	}//end FormularzA_ZS_GenerujRaportOZamówieniach

}//end namespace Interfejsy