///////////////////////////////////////////////////////////
//  FormularzA_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkowników.cs
//  Implementation of the Class FormularzA_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkowników
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:07
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator przegl¹da szczegó³owe informacje dotycz¹ce konkretnej rezerwacji
	/// u¿ytkownika.
	/// </summary>
	public class FormularzA_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkowników {

		private List(Rezerwacja) RezerwacjeU¿ytkowników;

		public FormularzA_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkowników(){

		}

		~FormularzA_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkowników(){

		}

		public void SprawdŸSzczegó³yRezerwacjiU¿ytkowników(){

		}

		public Ster_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkownika Ster_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkownika{
			get{
				return m_Ster_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkownika;
			}
			set{
				m_Ster_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkownika = value;
			}
		}

		public void WyœwietlRezerwacjeU¿ytkowników(){

		}

	}//end FormularzA_ZS_SprawdŸSzczegó³yRezerwacjiU¿ytkowników

}//end namespace Interfejsy