///////////////////////////////////////////////////////////
//  FormularzA_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT.cs
//  Implementation of the Class FormularzA_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:52:05
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator mo¿e przegl¹daæ listê wszystkich zamówieñ sprzêtu IT z³o¿onych w
	/// systemie.
	/// </summary>
	public class FormularzA_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT {

		private Historia zamówieñ Historia zamówieñ;

		public FormularzA_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT(){

		}

		~FormularzA_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT(){

		}

		public void Przegl¹dajWszystkieZamówieniaSprzêtuIT(){

		}

		public Ster_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT Ster_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT{
			get{
				return m_Ster_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT;
			}
			set{
				m_Ster_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT = value;
			}
		}

		public void WyœwietlZamówieniaSprzêtuIT(){

		}

	}//end FormularzA_ZS_Przegl¹dajWszystkieZamówieniaSprzêtuIT

}//end namespace Interfejsy