///////////////////////////////////////////////////////////
//  FormularzA_ZR_Zarz¹dzajRezerwacjami.cs
//  Implementation of the Class FormularzA_ZR_Zarz¹dzajRezerwacjami
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:45
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator nadzoruje wszystkie rezerwacje, umo¿liwiaj¹c ich dodawanie,
	/// edycjê i anulowanie.
	/// </summary>
	public class FormularzA_ZR_Zarz¹dzajRezerwacjami {

		public FormularzA_ZR_Zarz¹dzajRezerwacjami(){

		}

		~FormularzA_ZR_Zarz¹dzajRezerwacjami(){

		}

		public Ster_ZR_Zarz¹dzajRezerwacjami Ster_ZR_Zarz¹dzajRezerwacjami{
			get{
				return m_Ster_ZR_Zarz¹dzajRezerwacjami;
			}
			set{
				m_Ster_ZR_Zarz¹dzajRezerwacjami = value;
			}
		}

	}//end FormularzA_ZR_Zarz¹dzajRezerwacjami

}//end namespace Interfejsy