///////////////////////////////////////////////////////////
//  FormularzA_ZIT_WeryfikujDostêpnoœæSprzêtuIT.cs
//  Implementation of the Class FormularzA_ZIT_WeryfikujDostêpnoœæSprzêtuIT
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:19
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator zatwierdza dostêpnoœæ sprzêtu IT przed finalizacj¹ zamówienia.
	/// </summary>
	public class FormularzA_ZIT_WeryfikujDostêpnoœæSprzêtuIT {

		private Sprzêt IT sprzet;

		public FormularzA_ZIT_WeryfikujDostêpnoœæSprzêtuIT(){

		}

		~FormularzA_ZIT_WeryfikujDostêpnoœæSprzêtuIT(){

		}

		public Ster_ZIT_WeryfikujDostêpnoœæSprzêtuIT Ster_ZIT_WeryfikujDostêpnoœæSprzêtuIT{
			get{
				return m_Ster_ZIT_WeryfikujDostêpnoœæSprzêtuIT;
			}
			set{
				m_Ster_ZIT_WeryfikujDostêpnoœæSprzêtuIT = value;
			}
		}

		/// 
		/// <param name="sprzet"></param>
		public sbyte WeryfikujDostepnoscSprzetuIT(Sprzêt IT sprzet){

			return 0;
		}

		public string WyswietlDostepnoscSprzetuIT(){

			return "";
		}

	}//end FormularzA_ZIT_WeryfikujDostêpnoœæSprzêtuIT

}//end namespace Interfejsy