///////////////////////////////////////////////////////////
//  FormularzA_ZR_SprawdŸDostêpnoœæZasobów.cs
//  Implementation of the Class FormularzA_ZR_SprawdŸDostêpnoœæZasobów
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:32
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	/// <summary>
	/// Administrator weryfikuje, czy dany zasób jest dostêpny do rezerwacji w
	/// okreœlonym terminie.
	/// </summary>
	public class FormularzA_ZR_SprawdŸDostêpnoœæZasobów {

		public FormularzA_ZR_SprawdŸDostêpnoœæZasobów(){

		}

		~FormularzA_ZR_SprawdŸDostêpnoœæZasobów(){

		}

		/// 
		/// <param name="Rezerwacja"></param>
		public void srpawdzDostepnoscZasobu(int Rezerwacja){

		}

		public Ster_ZR_SprawdŸDostêpnoœæZasobów Ster_ZR_SprawdŸDostêpnoœæZasobów{
			get{
				return m_Ster_ZR_SprawdŸDostêpnoœæZasobów;
			}
			set{
				m_Ster_ZR_SprawdŸDostêpnoœæZasobów = value;
			}
		}

		public void WyswietlDostepnoscSprzetuIT(){

		}

	}//end FormularzA_ZR_SprawdŸDostêpnoœæZasobów

}//end namespace Interfejsy