///////////////////////////////////////////////////////////
//  FormularzA_ZR_WyœlijPowiadomienieORezerwacji.cs
//  Implementation of the Class FormularzA_ZR_WyœlijPowiadomienieORezerwacji
//  Generated by Enterprise Architect
//  Created on:      28-mar-2025 21:51:42
//  Original author: bedna
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
namespace Interfejsy {
	/// <summary>
	/// Administrator informuje u¿ytkownika o zatwierdzeniu jego rezerwacji.
	/// </summary>
	public class FormularzA_ZR_WyœlijPowiadomienieORezerwacji {

		public FormularzA_ZR_WyœlijPowiadomienieORezerwacji(){

		}

		~FormularzA_ZR_WyœlijPowiadomienieORezerwacji(){

		}

		public Ster_ZR_WyœlijPowiadomienieORezerwacji Ster_ZR_WyœlijPowiadomienieORezerwacji{
			get{
				return m_Ster_ZR_WyœlijPowiadomienieORezerwacji;
			}
			set{
				m_Ster_ZR_WyœlijPowiadomienieORezerwacji = value;
			}
		}

		/// 
		/// <param name="Rezerwacja"></param>
		public void WyslijPowiadomienieORezerwacji(Rezerwacja Rezerwacja){

		}

	}//end FormularzA_ZR_WyœlijPowiadomienieORezerwacji

}//end namespace Interfejsy